### ISSUE TITLE
Add level of availability for volunteers

### ISSUE THREAD

**Issue by tinnei** [sradu/covid-volunteers#6]
From #hwc-feature-request - 
> it would be super useful if the level of availability could be indicated (e.g. full-time, 4 hours per day, etc).

Suggestion:
- For new volunteers, we can prompt "Level of availability" as they get added into the project.
- For existing volunteers, we can send batch email to volunteers to ask them to add back their "Level of availability".

**Comment by wilsonw926** [comment]
@tinnei can we close this?
