### ISSUE TITLE
Be able to browse by skillset

### ISSUE THREAD

**Issue by heri** [sradu/covid-volunteers#8]
There are too many projects.Users should be able to quickly see where they can contribute without going to each one of them, especially if they have expert skills such as "Epidemiologist" or "Data science"

- [ ] Projects can have skills such as medical, finance, programming language
- [ ] Users can browse projects list by skills. Click on "medical" and then it would restrict the list to projects requiring medical help

**Comment by vcavallo** [comment]
https://github.com/sradu/covid-volunteers/pull/7 Will close this

**Comment by adrianthedev** [comment]
https://github.com/sradu/covid-volunteers/pull/12 will allow for paroject and volunteer filtering 🚀
